Avoid error when an input contains non-ASCII (1-byte) characters
wezm/titlecase pull request #11
Opened 2022-10-05 17:00 UTC by rnarkk

When an input contains non-ASCII (1-byte) characters, slicing &str by 1 violates the character boundaries and causes panic.

2022-10-05 22:50 UTC, wezm commented
Do you have a test case that causes a panic? The slice is guarded by the call to `starts_with_bracket` so it should never panic as we've checked that the first character is a valid single byte UTF-8 character. I.e. `(` `U+0028`.

2022-10-06 05:46 UTC, rnarkk commented
@wezm Please try to pass 'μ' as the input. Or any other greek letters ('π'). By the way, is there an option to convert only the Latin alphabet?

2022-10-06 06:05 UTC, wezm requested changes
> Please try to pass 'μ' as the input. Or any other greek letters ('π')

Ahh that does panic. Thanks.

Would be great if you could add a test as well. There's a bunch at the bottom of `lib.rs` that should serve as an example.

2022-10-06 06:05 UTC, wezm commented on src/lib.rs
> +        let rest = titlecase(&word.chars().skip(1).collect::<String>());
The slice in this case is guarded by `starts_with_bracket` so it can't cause a panic because we only get in here if the first character is `(`.

2022-10-06 06:05 UTC, wezm commented on src/lib.rs
> +    !word.is_empty() && word.chars().skip(1).collect::<String>().contains('/')
This one is the source of the panic. There's no need to allocate a string though, we can iterate over the characters and check if one is a slash.

Something like:

```rust
fn has_internal_slashes(word: &str) -> bool {
    word.chars().skip(1).any(|chr| chr == '/')
}
```

2022-10-06 06:09 UTC, wezm commented
> By the way, is there an option to convert only the Latin alphabet?

Do you mean something like passing in "μs" and have it come out as "us"? If so, that's probably out of scope for this library but there are others that could do it. I've used [deunicode](https://lib.rs/crates/deunicode) in another project.

2022-10-06 06:56 UTC, rnarkk commented
@wezm I mean I want to leave small greek letters as are when they are used as special mathematical operators or constants:

- π → π
- λ-calculus → λ-Calculus

2022-10-06 07:04 UTC, wezm commented
> @wezm I mean I want to leave small greek letters as are when they are used as special mathematical operators or constants:
> 
>     * π → π
> 
>     * λ-calculus → λ-Calculus

Ahh interesting. I see that it's upper-casing the greek letters too.

I can see why you'd want to avoid that. I think it would be fairly easy to support a mode where only ASCII characters were upper-cased.

2022-10-06 07:06 UTC, merged

2022-10-06 09:38 UTC, rnarkk commented
@wezm Thank you for reviewing and merging my request. Will look forward to the updated crate soon!

2022-10-06 23:21 UTC, wezm commented
v2.2.1 has been published now.